### ISSUE TITLE
Fix up links in the SVG document...

### ISSUE THREAD

**Issue by mamund** [koriym/app-state-diagram#15]
when multiple links appear on the same line in the SVG document, clicking on any of those links always routes you to the first document in the line. 

see source in example below:

[mvc-todo-alps.svg.txt](https://github.com/koriym/app-state-diagram/files/5538893/mvc-todo-alps.svg.txt)

**Comment by koriym** [comment]
before
![image](https://user-images.githubusercontent.com/529021/99145980-0c2bcd80-26b7-11eb-85b2-2bb0be75883b.png)

after
![image](https://user-images.githubusercontent.com/529021/99145927-86a81d80-26b6-11eb-99c4-96da9cd1c29d.png)

Multiple links are expressed as multiple arrows. SVG has a link in arrow, not only in the text label. The MVCtodo diagram was changed like this. @mamund Is this fine ?

**Comment by mamund** [comment]
yes. this is looking closer to what i'd expected. -- thanks.

**Comment by koriym** [comment]
<img width="150px" src="https://user-images.githubusercontent.com/529021/99200723-4e096080-27ea-11eb-8b73-fa0253150004.png"> 

The arrows lose their hyperlinks, but I'm going to do it this way because I think it makes the diagram easier to see.

**Comment by koriym** [comment]
source code:
```
    home->todoList [fontsize=12 label=<<table  border="0">
                       <tr><td style="font-size: 3pt;" align="left" href="http://google.com">listAll (safe)</td></tr>
                       <tr><td align="left" href="http://bing.com">goRelated (safe)</td></tr>
                       <tr><td align="left" href="http://bing.com">listActive (safe)</td></tr>
                       </table>>];
```
related: https://stackoverflow.com/questions/41307496/graphviz-multiple-links-per-label

**Comment by koriym** [comment]
![image](https://user-images.githubusercontent.com/529021/99205802-f4f6f800-27fc-11eb-9c9d-43a85e32ae57.png)

**Comment by koriym** [comment]
@mamund I realized that one transition requires multiple identities, which sometimes cannot be represented by a rel. This is necessary when there are different types and numbers of descriptors needed, for example. For example, free and paid members require different arguments for the same transition.

**Comment by mamund** [comment]
Yes. And they is another way to think of this situation.

Many links could return the same result/resource.

**Comment by mamund** [comment]
ans here's another real possibility...

assume an ALPS document defines several types of lists (`id="userlist"`, `id="factoryList"`, `id="productList:`, etc.). now assume that same document defines resource that contains a list of items that could return differenty *types* of items...

```
...
{
  "id" : "itemList", 
  "type" : "semantic", 
  "descriptors" : [
    {"href" : "#userList"},
    {"href" :"#factoryList"},
    {"href" : "#productList"}
  ]
}
...
```
Now, the ALPS document can include the following...

```
...
[
  {"id" : "users", "type" : "safe", "rt" : "#itemList"},
  {"id" : "factories", "type" : "safe", "rt" : "#itemList"},
  {"id" : "products", "type" : "safe", "rt" : "#itemList"}
]
...
```

right?

**Comment by koriym** [comment]
`itemList` returns `userList` if `users` transition used and
`itemList` returns `factories ` if `factories ` transition used.

Do I understand?

**Comment by mamund** [comment]
yep. or another link/context might return two of those three or even all
three (consider a dashboard resource or home list with short lists (top
five records) from each type.


Mike Amundsen

*APIs, Microservices, and Digital Transformation*
7310 Turfway Rd. Suite 550, Florence, KY, 41042


*+1.859.372.6517*
https://zoom.us/j/8593726715
http://linkedin.com/in/mamund
http://g.mamund.com/meetme
http://training.amundsen.com
http://twitter.com/mamund

**Comment by koriym** [comment]
"itemList can accept from any transition by users, factories or products but returns the same response." is also possible?
