### ISSUE TITLE
Support rendering document.title at top of diagram

### ISSUE THREAD

**Issue by mamund** [koriym/app-state-diagram#34]
I would like to be able to move the title of the document from the bottom of the rendered diagram to the top.

**Comment by koriym** [comment]
Good idea. 

@NaokiTsuchiya Thoughts?

**Comment by NaokiTsuchiya** [comment]
Here is a sample.

<img width="637" alt="title at top of diagram" src="https://user-images.githubusercontent.com/17171732/110438629-ea3cd780-80f9-11eb-8dcd-8e55f1631973.png">
