### ISSUE TITLE
Can not use external profile id as rt

### ISSUE THREAD

**Issue by NaokiTsuchiya** [koriym/app-state-diagram#44]
When root profile references `rt` from external profile like the following, throws `RtDescriptorMissingException`

```profile.json
{
  "$schema": "https://alps-io.github.io/schemas/alps.json",
  "alps": {
    "descriptor": [
      {"id": "Index", "descriptor": [
        {"href": "#foo"}
      ]},
      {"id": "foo", "type": "safe", "rt": "Foo.json#Foo"}
    ]
  }
}
```

```Foo.json
{
  "$schema": "https://alps-io.github.io/schemas/alps.json",
  "alps": {
    "descriptor": [
      {"id": "Foo", "descriptor": [
        {"href": "#id"}
      ]
      },
      {"id": "id"}
    ]
  }
}
```

The following commit is a red test.

https://github.com/koriym/app-state-diagram/commit/ed593cef46b2e62b05137eb97df56aa2813e4c7b

**Comment by koriym** [comment]
https://github.com/koriym/app-state-diagram/blob/26ec545ac98788fa1b06a57635d1a3c11589eea3/src/AlpsProfile.php#L201
