### ISSUE TITLE
Update breadcrumb list

### ISSUE THREAD

**Issue by poemn** [koriym/app-state-diagram#46]
There is a breadcrumb list in the header section of the document, but there is no hierarchical structure and it is not appropriate.

<img width="197" alt="image" src="https://user-images.githubusercontent.com/529021/114198300-1e701600-998e-11eb-8b32-a9ea7663e09f.png">

This PR changes the separator (>) between Home, Asd, and {semantic} to a pipe (|).
See below.

before :
```
home > asd > About
```

after :
```
home | asd | json
```

**Comment by koriym** [comment]
@mamund Thoughts ?

**Comment by mamund** [comment]
i have no strong feelings on the separator value.  the bar would be fine.

an valuable enhancement (which might be out of scope here) would be to output semantic HTML that would allow support for customizing the separator (possibly the whole menu) using CSS.

see https://stackoverflow.com/questions/5688791/separators-for-navigation for some rough ideas.

**Comment by koriym** [comment]
Thanks for the comment. Semantic HTML would be ideal, but We are currently using fixed GH CSS, so that will be a future project. Again, Thanks for the information.

**Comment by koriym** [comment]
I changed to `home | asd | source`

(The source might be XML)
