### ISSUE TITLE
Unexpected results for external values on HREF 

### ISSUE THREAD

**Issue by mamund** [koriym/app-state-diagram#47]
the ability to use full URIs for HREF values exhibit unexpected results.

assume this sample ALPS document:
```
{
  "alps" : {
    "version" : "1.0",
    "title" : "Testing External References",
    "descriptor" : [
      {"href": "https://rwmbook.github.io/alps-documents/related/related.json#home"}
    ]
  }
}
```

now...

1) when processed by ASD, the results look identical to the results found here: https://rwmbook.github.io/alps-documents/mru/index.html

Note the `title` from the source document is replaced by the `title` in the reference document.

2) adding a second external reference:
```
{
  "alps" : {
    "version" : "1.0",
    "title" : "Testing External References",
    "descriptor" : [
      {"href": "https://rwmbook.github.io/alps-documents/related/related.json#home"},
      {"href": "https://rwmbook.github.io/alps-documents/mru/mru.json#home"}
    ]
  }
}
```

now the results seems to be a *merge* of the two. but there are inconsistencies.  

* Note the title is still replaced but this time by the `title` of the second external reference. 
* inspecting the two external references shows that they both contain defintiions for a `home` semantic element. 
* Note that the `home` semantic element (a resource expression) shown here is the one from the second reference in the source document.  However, it is missing a sub descriptor (`relatedLink`) even though there is one in the `home` descriptor of the second reference. It looks like there are overwrites here which should be merges?

3) finally, let's flip the order of the external references:
```
{
  "alps" : {
    "version" : "1.0",
    "title" : "Testing External References",
    "descriptor" : [
      {"href": "https://rwmbook.github.io/alps-documents/mru/mru.json#home"},
      {"href": "https://rwmbook.github.io/alps-documents/related/related.json#home"}
    ]
  }
}
```
now the results show that the second external reference has overwritten (not merged) matching element from the first.

I expected any "clashes" of descriptors to result in a faithful combining of the two (or more) elements. I also expected the `title` to  be that of the source document (not the last reference). 

I think i am OK with the general results (the merging of the two documents as long as it is done faithfully. it has implications for creating smaller ALPS documents and then using a "parent" document to combine them easily. that could be handy.

**Comment by koriym** [comment]
![image](https://user-images.githubusercontent.com/529021/116001398-3783f280-a62f-11eb-844d-f068f750c9a5.png)

This result was generated by adding the following entry to `todoItem`.

```
{"id": "goBlogPosting", "type": "safe", "rt": "https://koriym.github.io/app-state-diagram/blog/profile.json#BlogPosting"}
```

**Comment by koriym** [comment]
Although `goBlogPosting` only links to `BlogPosting`, other semantic descriptors (include application state) can be "crawled" from the `descriptor` that `BlogPosting` has. 

There is no `Index` compared to the original as following. This is because there is no link "to" the Index.

![image](https://user-images.githubusercontent.com/529021/116001539-e45e6f80-a62f-11eb-988e-6e0a332d01dd.png)

**Comment by koriym** [comment]
The previous version imported external files with all semantic descriptors, but now it imports the target, the target's subtree, and the links from the target. The link is recursive and in many cases, all diagrams are imported.

Also, You can import several profiles and combine them, or you can use a vocabulary-only profile without links.

**Comment by koriym** [comment]
@mamund What do you think?

**Comment by mamund** [comment]
looks good to me. will do some testing over the next day or so to find edges, etc.

I assume the title of the "host" document is the title of the diagram. for example, what is the title here:

```
{
  "alps" : {
    "version" : "1.0",
    "title" : "Testing External References",
    "descriptor" : [
      {"href": "https://rwmbook.github.io/alps-documents/mru/mru.json#home"},
      {"href": "https://rwmbook.github.io/alps-documents/related/related.json#goRelated"}
    ]
  }
}
```
thanks

@mamund

**Comment by koriym** [comment]
> I assume the title of the "host" document is the title of the diagram. for example, what is the title here:

Yes, this is fixed. 

I still need some more time to release. I will let you know when it's ready. Thanks.

**Comment by koriym** [comment]
You can confirm the tile holds "MVC Todo" which is importing blog profile In the figure above.

**Comment by koriym** [comment]
@mamund Fixed and released as https://github.com/koriym/app-state-diagram/releases/tag/0.3.5 !
