### ISSUE TITLE
Add footer to tag pages in the documentation

### ISSUE THREAD

**Issue by mamund** [koriym/app-state-diagram#49]
very much like the rendering of `tag` values on the home page of the ALPS profile documentation.

would also like to see the typical navigation footer appear at the bottom of these pages to maket it easier to naivgate between tag pages and other pages in the documentation.

please consider adding:

`home > asd > {tag}`

as the footer for all tag pages.

**Comment by koriym** [comment]
@NaokiTsuchiya will do in early May. Arigato.

**Comment by mamund** [comment]
thanks.
