### ISSUE TITLE
add support for the text property of a descriptor

### ISSUE THREAD

**Issue by mamund** [koriym/app-state-diagram#50]
I often use the `text` property of a `desriptor` for a short human-readable documentation string. I'd like to see that in the rendering of the ASD documentation, too.

minimum: it should appear alongside all the other property values on the detail pages like `type`, `doc`, `rel`, `tag`, and `rt`.

optimum: it would be great if the `text` value appeared in any listings (home page, `tag` pages, the `descriptor` tables), too.  

for example, on the home page, insert that text after the `type` value:
`<li><a href="docs/unsafe.doPersonCreate.html">doPersonCreate</a> (unsafe), {text}</li>`

and, for descriptor list tables, add another column to the right of the `type` value:

```
<table>
 <thead>
 <tr>
 <th>id</th>
 <th>type</th>
 <th>text</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td><a href="semantic.home.html">home</a></td>
 <td>semantic</td>
 <td>{text}</td>
 </tr>
 <tr>
 <td><a href="safe.goHome.html">goHome</a></td>
 <td>safe</td>
 <td>{text}</td>
 </tr>
 <tr>
 <td><a href="safe.goPersonCollection.html">goPersonCollection</a></td>
 <td>safe</td>
 <td>{text}</td>
 </tr>
 </tbody>
 </table>
```

**Comment by koriym** [comment]
Aren't you talking about the `title` tag, not the `text` tag?

**Comment by mamund** [comment]
ahhh. is that right? we use title, not text. 

somehow i do not seem to know this specification I have spent so long working in?????

maybe this is only a bug in my head!?

I will test and, if needed, close this issue.

thanks.

**Comment by koriym** [comment]
> somehow i do not seem to know this specification I have spent so long working in?????

No worry. This happens to all of us from time to time!

Yes semantic descriptor page has `title`, Also the `optimum` case is ready with #55 PR

**Comment by koriym** [comment]
So please test with the new release which I will do now.

**Comment by koriym** [comment]
@mamund Release announced https://twitter.com/koriym/status/1387257213954125830?s=20 !

**Comment by mamund** [comment]
thanks.
