### ISSUE TITLE
Getting error attempting to parse XML document

### ISSUE THREAD

**Issue by mamund** [koriym/app-state-diagram#58]
after running the update/install for later version i see:

given the following XML profile:
https://raw.githack.com/alps-io/profiles/master/xml/to-do.xml

when i run the ASD tool i get the following response:
```
Parse error on line 1:
<alps version="1.0">
^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' 
 in /home/mca/.config/composer/vendor/koriym/app-state-diagram/src/JsonDecode.php:55
```

**Comment by mamund** [comment]
i just created a JSON "host" document and pointed to a node in an XML external file:

https://raw.githubusercontent.com/alps-io/alps-asd-playground/main/xml-samples/test.json

and this works as expected.

is it correct to say that, right now, ASD does not open XML files directly? only as an external reference?

is yes, you can close out this issue

thanks.

**Comment by koriym** [comment]
Confirmed. It should work with your operation.

**Comment by mamund** [comment]
thanks for the update.

**Comment by koriym** [comment]
@mamund Fix and released!

**Comment by mamund** [comment]
confirmed. this now works with local XML documents. 

thanks.
