### ISSUE TITLE
Raw descriptor output

### ISSUE THREAD

**Issue by koriym** [koriym/app-state-diagram#60]
Raw descriptor output should be checked. 
There are currently a few things to consider.

* XML is also output as JSON
* Some elements are missing.

Or don't we need this feature in the first place?

**Comment by koriym** [comment]
@mamund Do we really needs this feature ?

**Comment by mamund** [comment]
what is this feature about? i don't recall us dsicussing this?

**Comment by koriym** [comment]
It's about the "source" link raw JSON.

https://koriym.github.io/app-state-diagram/blog/docs/semantic.About.html

This is for the partial raw JSON, (but it is currently broken.)
I think we can remove this feature.

**Comment by mamund** [comment]
yes -- since i cannot figure out what the feature really is, i can't come up with a reason to use it<g>.

if i requested this feature, i apologize.

**Comment by koriym** [comment]
No worries. I remove it. 

Thanks for your comment.
