### ISSUE TITLE
Support link element a child of descriptor 

### ISSUE THREAD

**Issue by NaokiTsuchiya** [koriym/app-state-diagram#71]
In the [spec](https://datatracker.ietf.org/doc/html/draft-amundsen-richardson-foster-alps-07#section-2.2.10),  link element a child element of the `alps` and the `descriptor` elements.

In my idea, can connect profile and schema like the following.

```xml
<descriptor id="Blog">
  <link rel="schema" href="../schema/blog.json" />
</descriptor>
```

```json
{
  "descriptor": [
    {"id": "Blog", "link": {"rel": "schema", "href": "../schema/blog.json"}}
  ]
}
```

**Comment by koriym** [comment]
@mamund

When the semantic descriptor needs `relation`, Which should we use?

```
<descriptor id="Blog">
  <link rel="schema" href="../schema/blog.json" />
</descriptor>
```

or 

```
<descriptor id="Blog" rel="schema" href="../schema/blog.json">
```

The explanation is given

at the `link` section.

> An element that identifies a link between the current ALPS element
   and some other (possibly external) resource.  MAY be a child element
   of the 'alps' and the 'descriptor' elements.
   
https://datatracker.ietf.org/doc/html/draft-amundsen-richardson-foster-alps-07#section-2.2.10
   
 at the `rel` section

>    Appears as a property of 'link' and 'descriptor'.

https://datatracker.ietf.org/doc/html/draft-amundsen-richardson-foster-alps-07#section-2.2.12

**Comment by koriym** [comment]
@mamund We notice our misunderstanding.

```
<descriptor id="Blog" rel="schema" href="../schema/blog.json">
```
This is not valid. `href` can only point to the ALPS profile. Right?

**Comment by mamund** [comment]
I use the `rel` to hold content i expect to appear within the runtime document. 

```
<descriptor id="goBlogList" type="safe" rel="blog collection"  title="Blog List" />

BECOMES

<a href="..." id="goBlogPost" rel="blog collection">Blog List</a>
```

I use the `link` to hold content i expect to appear as part of the document's metadata or documentation

```
<descriptor id="goBlogList" type="safe" rel="blog collection"  title="Blog List">
   <link href="http://api.examples.org/blog/list" rel="help" />
</descriptor>   

BECOMES

<link href="http://api.example.org/blogList" id="goBlogPost" rel="blog help" />
```

**Comment by koriym** [comment]
Great example! Now totally clarified. Thanks.

**Comment by koriym** [comment]
What about the `semantic` has `rel`?
(I thought it might be something like IANA words and phrases to represent tags.)

```
<descriptor id="BlogList" type="semantic" rel="collection"/>
```

Is this valid?

**Comment by mamund** [comment]
technically valid (per spec) but i have not found a use for this combination.

**Comment by koriym** [comment]
Ok. Thanks.

**Comment by koriym** [comment]
Right now, this `link` is not shown in ASD document.

```
<descriptor id="goBlogList" type="safe" rel="blog collection"  title="Blog List">
   <link href="http://api.examples.org/blog/list" rel="help" />
</descriptor>   
```

![image](https://user-images.githubusercontent.com/529021/120965736-3d2d3600-c7a0-11eb-9732-a2c559fdbbc0.png)

Maybe we need another `link` table after the descriptor in the same style.

@NaokiTsuchiya @mamund Thoughts?

**Comment by mamund** [comment]
If i remember correctly, no LINK elements appear in ASD documents.

to start, I'd like to see LINK elements appear in the list of metadata near the top of each ASD document. I would expect to use this to point to additional documentation or other reference material. This would be very much like the way I use DEF elements.

just an idea.

**Comment by koriym** [comment]
>to start, I'd like to see LINK elements appear in the list of metadata near the top of each ASD document. I would expect to use this to point to additional documentation or other reference material. This would be very much like the way I use DEF elements.

Already supported from the "this morning release" thanks to @NaokiTsuchiya 's contribution. Please try!

**Comment by mamund** [comment]
will do. thanks.

**Comment by koriym** [comment]
@NaokiTsuchiya Ok, Let's go next step!

**Comment by NaokiTsuchiya** [comment]
Schema update.
https://github.com/alps-io/schemas/pull/9
