### ISSUE TITLE
Display mode

### ISSUE THREAD

**Issue by koriym** [koriym/app-state-diagram#74]
![image](https://user-images.githubusercontent.com/529021/121980394-d2df4b80-cdc6-11eb-8170-a2b8ec8edc21.png)

[original]

![image](https://user-images.githubusercontent.com/529021/121981364-7715c200-cdc8-11eb-8984-2d5a6cae51ae.png)

The above example displays the `title` instead of the `id` of the semantic descriptor.

Wouldn't this paraphrase help the business people understand?

**Comment by mamund** [comment]
this would be a nice enhancement. would make a good CLI or config option.

maybe an opton to see both?

**Comment by koriym** [comment]
> maybe an opton to see both?

Yes!

**Comment by koriym** [comment]
We're thinking of dropping support for CLI options and just using config. What do you think?

https://github.com/koriym/app-state-diagram/pull/73

**Comment by koriym** [comment]
In Japanese title

![image](https://user-images.githubusercontent.com/529021/121984851-acbda980-cdce-11eb-950b-7055dfe1c09c.png)

**Comment by mamund** [comment]
> We're thinking of dropping support for CLI options and just using config. What do you think?
> 
> #73

Config file is cool. Again, maybe support both?
